const EXERCISES = [
  {'name':'Ab Coaster','measurement':'reps','mods':['machine'],'muscles':['abs']},
  {'name':'Ab Wheel Rollout','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Archer Row','measurement':'reps','mods':['free weight'],'muscles':['biceps','abs','traps','lats','lower back']},
  {'name':'Back Extension','measurement':'reps','mods':['body weight'],'muscles':['lower back']},
  {'name':'Back Extension','measurement':'reps','mods':['machine'],'muscles':['lower back']},
  {'name':'Backward Leg Extension','measurement':'reps','mods':['machine','each leg','prone'],'muscles':['hamstrings','glutes']},
  {'name':'Backward Leg Extension','measurement':'reps','mods':['machine','each leg','standing'],'muscles':['hamstrings','glutes']},
  {'name':'Bicep Curl','measurement':'reps','mods':['free weight','each arm'],'muscles':['biceps']},
  {'name':'Bicep Curl','measurement':'reps','mods':['free weight','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl','measurement':'reps','mods':['machine','iso','each arm'],'muscles':['biceps']},
  {'name':'Bicep Curl','measurement':'reps','mods':['machine','iso','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['biceps']},
  {'name':'Bicep Curl','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['biceps']},
  {'name':'Bicep Curl','measurement':'reps','mods':['machine','each arm','standing'],'muscles':['biceps']},
  {'name':'Bicep Curl','measurement':'reps','mods':['machine','both arms','standing'],'muscles':['biceps']},
  {'name':'Bicep Curl, Closed Grip','measurement':'reps','mods':['free weight','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl, Closed Grip','measurement':'reps','mods':['free weight','each arm'],'muscles':['biceps']},
  {'name':'Bicep Curl, Closed Grip','measurement':'reps','mods':['machine','iso','each arm'],'muscles':['biceps']},
  {'name':'Bicep Curl, Closed Grip','measurement':'reps','mods':['machine','iso','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl, Drag','measurement':'reps','mods':['free weight','each arm'],'muscles':['biceps','forearms']},
  {'name':'Bicep Curl, Drag','measurement':'reps','mods':['free weight','both arms'],'muscles':['biceps','forearms']},
  {'name':'Bicep Curl, Hammer','measurement':'reps','mods':['free weight','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl, Hammer','measurement':'reps','mods':['free weight','each arm'],'muscles':['biceps']},
  {'name':'Bicep Curl, Preacher','measurement':'reps','mods':['free weight','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl, Preacher','measurement':'reps','mods':['free weight','each arm'],'muscles':['biceps']},
  {'name':'Bicep Curl, Side','measurement':'reps','mods':['free weight','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl, Side','measurement':'reps','mods':['machine','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl, Wide Grip','measurement':'reps','mods':['free weight','both arms'],'muscles':['biceps']},
  {'name':'Bicep Curl, Zottman','measurement':'reps','mods':['free weight','each arm'],'muscles':['biceps','forearms']},
  {'name':'Bicep Curl, Zottman','measurement':'reps','mods':['free weight','both arms'],'muscles':['biceps','forearms']},
  {'name':'Bicycles','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Boat Pose','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Calf Raise','measurement':'reps','mods':['body weight','each leg'],'muscles':['calves']},
  {'name':'Calf Raise','measurement':'reps','mods':['body weight','both legs'],'muscles':['calves']},
  {'name':'Calf Raise','measurement':'reps','mods':['machine','each leg','sitting'],'muscles':['calves']},
  {'name':'Calf Raise','measurement':'reps','mods':['machine','both legs','sitting'],'muscles':['calves']},
  {'name':'Calf Raise','measurement':'reps','mods':['machine','each leg','standing'],'muscles':['calves']},
  {'name':'Calf Raise','measurement':'reps','mods':['machine','both legs','standing'],'muscles':['calves']},
  {'name':'Chest Press','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press','measurement':'reps','mods':['machine','both arms','standing'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Converging','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Converging','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Converging','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Converging','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Converging','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Converging','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Low Converging','measurement':'reps','mods':['machine','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Low Converging','measurement':'reps','mods':['machine','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Wide','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Wide','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Wide','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Wide','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Wide','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chest Press, Wide','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Chin Up','measurement':'reps','mods':['body weight','both arms'],'muscles':['biceps','lats']},
  {'name':'Chin Up','measurement':'reps','mods':['machine','both arms','assisted'],'muscles':['biceps','lats']},
  {'name':'Chin Up','measurement':'reps','mods':['body weight','each arm'],'muscles':['biceps','lats']},
  {'name':'Climber Taps','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Crunch','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Crunch, Arms High','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Crunch, Bear','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Crunch, Cable Pull Down','measurement':'reps','mods':['machine'],'muscles':['abs']},
  {'name':'Crunch, Knee to Elbow','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Crunch, Physioball','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Crunch, Raised Knees','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Crunch, Side','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Crunchy Frog','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Dead Bug','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Dead Lift','measurement':'reps','mods':['free weight'],'muscles':['quads','hamstrings','traps','lower back','glutes']},
  {'name':'Dead Lift','measurement':'reps','mods':['machine'],'muscles':['quads','hamstrings','traps','lower back','glutes']},
  {'name':'Dead Lift, Romanian','measurement':'reps','mods':['free weight'],'muscles':['quads','hamstrings','traps','lower back','glutes']},
  {'name':'Dead Lift, Romanian','measurement':'reps','mods':['machine'],'muscles':['quads','hamstrings','traps','lower back','glutes']},
  {'name':'Decline Press','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Converging','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Converging','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Converging','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Converging','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Converging','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Converging','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Wide','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Wide','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Wide','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Wide','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Wide','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Decline Press, Wide','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Dip, Hanging','measurement':'reps','mods':['body weight'],'muscles':['triceps']},
  {'name':'Dip, Ledge','measurement':'reps','mods':['body weight'],'muscles':['triceps']},
  {'name':'Dip, Seated','measurement':'reps','mods':['machine','iso','both arms'],'muscles':['triceps']},
  {'name':'Elevated Bird Dog','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Fifer Scissor','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Flutter Kick','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Flutter Kick, Boat Pose','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Front Raise','measurement':'reps','mods':['free weight','each arm'],'muscles':['front delts']},
  {'name':'Front Raise','measurement':'reps','mods':['free weight','both arms'],'muscles':['front delts']},
  {'name':'Front Raise','measurement':'reps','mods':['machine','each arm'],'muscles':['front delts']},
  {'name':'Front Raise','measurement':'reps','mods':['machine','both arms'],'muscles':['front delts']},
  {'name':'Front Raise, Hammer Grip','measurement':'reps','mods':['free weight','each arm'],'muscles':['front delts']},
  {'name':'Front Raise, Hammer Grip','measurement':'reps','mods':['free weight','both arms'],'muscles':['front delts']},
  {'name':'Front Raise, Hammer Grip','measurement':'reps','mods':['machine','each arm'],'muscles':['front delts']},
  {'name':'Front Raise, Hammer Grip','measurement':'reps','mods':['machine','both arms'],'muscles':['front delts']},
  {'name':'Grip Crush','measurement':'reps','mods':['free weight','each arm'],'muscles':['forearms']},
  {'name':'Grip Crush','measurement':'reps','mods':['free weight','both arms'],'muscles':['forearms']},
  {'name':'Grip Crush','measurement':'reps','mods':['machine','each arm'],'muscles':['forearms']},
  {'name':'Grip Crush','measurement':'reps','mods':['machine','both arms'],'muscles':['forearms']},
  {'name':'Hamstring Curl','measurement':'reps','mods':['machine','each leg','sitting'],'muscles':['hamstrings']},
  {'name':'Hamstring Curl','measurement':'reps','mods':['machine','both legs','sitting'],'muscles':['hamstrings']},
  {'name':'Hamstring Curl','measurement':'reps','mods':['machine','each leg','prone'],'muscles':['hamstrings']},
  {'name':'Hamstring Curl','measurement':'reps','mods':['machine','both legs','prone'],'muscles':['hamstrings']},
  {'name':'Hanging Leg Raise, Bent Knee','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Hanging Leg Raise, Straight','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'High Pull','measurement':'reps','mods':['free weight'],'muscles':['front delts','traps']},
  {'name':'High Pull','measurement':'reps','mods':['machine'],'muscles':['front delts','traps']},
  {'name':'Hip Flexor','measurement':'reps','mods':['machine'],'muscles':['hip flexors']},
  {'name':'Hip Rock N Raise','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Hip Up','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Hundreds','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'In and Out','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Inchworm Slide','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Incline Press','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Converging','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Converging','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Converging','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Converging','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Converging','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Converging','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Wide','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Wide','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Wide','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Wide','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Wide','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Incline Press, Wide','measurement':'reps','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Kneeling Chop','measurement':'reps','mods':['machine'],'muscles':['abs','obliques']},
  {'name':'L-Sit','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Lat Pulldown, Normal','measurement':'reps','mods':['machine','both arms'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Normal','measurement':'reps','mods':['machine','iso'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Normal','measurement':'reps','mods':['machine','each arm'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Normal','measurement':'reps','mods':['machine','iso','each arm'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Palms In','measurement':'reps','mods':['machine','both arms'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Palms In','measurement':'reps','mods':['machine','iso'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Palms In','measurement':'reps','mods':['machine','each arm'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Palms In','measurement':'reps','mods':['machine','iso','each arm'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Wide','measurement':'reps','mods':['machine','both arms'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Wide','measurement':'reps','mods':['machine','iso'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Wide','measurement':'reps','mods':['machine','each arm'],'muscles':['biceps','lats']},
  {'name':'Lat Pulldown, Wide','measurement':'reps','mods':['machine','iso','each arm'],'muscles':['biceps','lats']},
  {'name':'Lateral Raise','measurement':'reps','mods':['free weight','each arm'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise','measurement':'reps','mods':['free weight','both arms'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise','measurement':'reps','mods':['machine','each arm'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise','measurement':'reps','mods':['machine','both arms'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise, Bent Over','measurement':'reps','mods':['free weight','each arm'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise, Bent Over','measurement':'reps','mods':['free weight','both arms'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise, Bent Over','measurement':'reps','mods':['machine','each arm'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise, Bent Over','measurement':'reps','mods':['machine','both arms'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise, Hammer Grip','measurement':'reps','mods':['free weight','each arm'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise, Hammer Grip','measurement':'reps','mods':['free weight','both arms'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise, Hammer Grip','measurement':'reps','mods':['machine','each arm'],'muscles':['center delts','rear delts']},
  {'name':'Lateral Raise, Hammer Grip','measurement':'reps','mods':['machine','both arms'],'muscles':['center delts','rear delts']},
  {'name':'Laying Leg Raise, Horizontal','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Laying Leg Raise, Vertical','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Laying Toe Taps','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Leg Climber','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Leg Press','measurement':'reps','mods':['machine','each leg'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Leg Press','measurement':'reps','mods':['machine','both legs'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Low Pull','measurement':'reps','mods':['free weight'],'muscles':['front delts','traps']},
  {'name':'Low Pull','measurement':'reps','mods':['machine'],'muscles':['front delts','traps']},
  {'name':'Lunge','measurement':'reps','mods':['body weight'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Lunge, Overhead Weight','measurement':'reps','mods':['free weight'],'muscles':['center delts','front delts','rear delts','quads','hamstrings','glutes']},
  {'name':'Mogul Jump','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Mountain Climbers','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Opposite Arm/Leg Raise','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Pectoral Fly','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pectoral Fly','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pectoral Fly','measurement':'reps','mods':['machine','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pectoral Fly','measurement':'reps','mods':['machine','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pectoral Fly, Incline','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pectoral Fly, Incline','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Physioball Buzzsaw','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Physioball Circles','measurement':'time','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Physioball Pike','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Pike Press','measurement':'reps','mods':['body weight'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Plank','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Plank to Down Dog','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Plank, Arm Raises','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Plank, Crunches','measurement':'time','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Plank, Leg Raises','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Plank, Moving Shuffle','measurement':'time','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Plank, RKC','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Plank, Star','measurement':'time','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Plank, Up and downs','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Plank, Walk Ins','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Prone Plate Switch','measurement':'time','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Pull Up','measurement':'reps','mods':['body weight','both arms'],'muscles':['biceps','lats']},
  {'name':'Pull Up','measurement':'reps','mods':['machine','both arms','assisted'],'muscles':['biceps','lats']},
  {'name':'Pull Up','measurement':'reps','mods':['body weight','each arm'],'muscles':['biceps','lats']},
  {'name':'Pulse Up','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Pushup','measurement':'reps','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup','measurement':'reps','mods':['body weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup, Cobra','measurement':'reps','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup, Decline','measurement':'reps','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup, Decline','measurement':'reps','mods':['body weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup, Diamond','measurement':'reps','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup, Incline','measurement':'reps','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup, Incline','measurement':'reps','mods':['body weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup, Knees','measurement':'reps','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Pushup, Knees','measurement':'reps','mods':['body weight','each arm'],'muscles':['triceps','front delts','pectorals']},
  {'name':'Quadricep Extension','measurement':'reps','mods':['machine','each leg'],'muscles':['quads']},
  {'name':'Quadricep Extension','measurement':'reps','mods':['machine','both legs'],'muscles':['quads']},
  {'name':'Raised Leg Circles','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Raised Leg Splits','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Raised Leg Swings','measurement':'time','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Rear Deltoid Fly','measurement':'reps','mods':['machine','both arms'],'muscles':['rear delts']},
  {'name':'Rear Deltoid Fly','measurement':'reps','mods':['machine','each arm'],'muscles':['rear delts']},
  {'name':'Rear Deltoid Fly','measurement':'reps','mods':['free weight','each arm'],'muscles':['rear delts']},
  {'name':'Rear Deltoid Fly','measurement':'reps','mods':['free weight','both arms'],'muscles':['rear delts']},
  {'name':'Reverse Superman','measurement':'time','mods':['body weight'],'muscles':['abs']},
  {'name':'Rocky Abs','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Roman Chair','measurement':'reps','mods':['body weight'],'muscles':['lower back']},
  {'name':'Rotational Cable Pull','measurement':'reps','mods':['machine'],'muscles':['abs','obliques']},
  {'name':'Row, Bent Over','measurement':'reps','mods':['machine','both arms'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, Bent Over','measurement':'reps','mods':['free weight','each arm'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, Bent Over','measurement':'reps','mods':['free weight','both arms'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, Face Pull','measurement':'reps','mods':['machine','both arms'],'muscles':['traps','lats']},
  {'name':'Row, Low','measurement':'reps','mods':['machine','both arms','sitting'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, Low','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, Low','measurement':'reps','mods':['machine','both arms','standing'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, Normal','measurement':'reps','mods':['machine','sitting'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, Normal','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, Normal','measurement':'reps','mods':['machine','both arms','standing'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, T-Bar (45 deg)','measurement':'reps','mods':['machine','both arms'],'muscles':['rear delts','traps','lats']},
  {'name':'Row, T-Bar (45 deg)','measurement':'reps','mods':['machine','iso','both arms'],'muscles':['rear delts','traps','lats']},
  {'name':'Running Man','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Russian Twist, Barbell','measurement':'reps','mods':['free weight'],'muscles':['abs','obliques']},
  {'name':'Russian Twist, Decline Medicine Ball','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Russian Twist, Medicine Ball','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Scissor Kick','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Shoulder Press','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press','measurement':'reps','mods':['machine','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press','measurement':'reps','mods':['machine','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press','measurement':'reps','mods':['machine','iso','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press','measurement':'reps','mods':['machine','iso','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press, Hammer Grip','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press, Hammer Grip','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press, Hammer Grip','measurement':'reps','mods':['machine','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press, Hammer Grip','measurement':'reps','mods':['machine','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press, Hammer Grip','measurement':'reps','mods':['machine','iso','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shoulder Press, Hammer Grip','measurement':'reps','mods':['machine','iso','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals']},
  {'name':'Shrug, Front','measurement':'reps','mods':['free weight'],'muscles':['traps']},
  {'name':'Shrug, Front','measurement':'reps','mods':['machine'],'muscles':['traps']},
  {'name':'Shrug, Side','measurement':'reps','mods':['free weight','each arm'],'muscles':['traps']},
  {'name':'Shrug, Side','measurement':'reps','mods':['free weight','both arms'],'muscles':['traps']},
  {'name':'Shrug, Side','measurement':'reps','mods':['machine','each arm'],'muscles':['traps']},
  {'name':'Shrug, Side','measurement':'reps','mods':['machine','both arms'],'muscles':['traps']},
  {'name':'Side Jack Knives','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Side Plank','measurement':'time','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Side Plank, Rotational','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Single Arm Wall Push','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Sit up, Butterfly','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Sit up, Straight Leg','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Sit up, Wide Leg','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Sitting Punches','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Squat','measurement':'reps','mods':['body weight'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Squat','measurement':'reps','mods':['machine'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Squat, Bulgarian Split','measurement':'reps','mods':['body weight'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Squat, Front','measurement':'reps','mods':['free weight'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Squat, Front','measurement':'reps','mods':['machine'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Squat, Jump','measurement':'reps','mods':['body weight'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Squat, Skater','measurement':'reps','mods':['body weight'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Squat, Wall','measurement':'reps','mods':['body weight'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Step up','measurement':'reps','mods':['body weight'],'muscles':['quads','hamstrings','glutes']},
  {'name':'Superman','measurement':'time','mods':['body weight'],'muscles':['lower back']},
  {'name':'Swiss Ball Jack Knife','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Thigh, Inner','measurement':'reps','mods':['machine'],'muscles':['inner thigh']},
  {'name':'Thigh, Outer','measurement':'reps','mods':['machine'],'muscles':['outer thigh']},
  {'name':'Trap Raise','measurement':'reps','mods':['free weight','each arm'],'muscles':['center delts','front delts','rear delts','traps']},
  {'name':'Trap Raise','measurement':'reps','mods':['free weight','both arms'],'muscles':['center delts','front delts','rear delts','traps']},
  {'name':'Tricep Extension','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps']},
  {'name':'Tricep Extension','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps']},
  {'name':'Tricep Extension, Bent Over','measurement':'reps','mods':['free weight','each arm'],'muscles':['triceps']},
  {'name':'Tricep Extension, Bent Over','measurement':'reps','mods':['machine','each arm'],'muscles':['triceps']},
  {'name':'Tricep Extension, Bent Over','measurement':'reps','mods':['free weight','both arms'],'muscles':['triceps']},
  {'name':'Tricep Extension, Bent Over','measurement':'reps','mods':['machine','both arms'],'muscles':['triceps']},
  {'name':'Tricep Extension, Overhead','measurement':'reps','mods':['machine','iso','each arm','sitting'],'muscles':['triceps']},
  {'name':'Tricep Extension, Overhead','measurement':'reps','mods':['machine','iso','both arms','sitting'],'muscles':['triceps']},
  {'name':'Tricep Extension, Overhead','measurement':'reps','mods':['free weight','each arm','sitting'],'muscles':['triceps']},
  {'name':'Tricep Extension, Overhead','measurement':'reps','mods':['free weight','both arms','sitting'],'muscles':['triceps']},
  {'name':'Tricep Extension, Overhead','measurement':'reps','mods':['free weight','each arm','prone'],'muscles':['triceps']},
  {'name':'Tricep Extension, Overhead','measurement':'reps','mods':['free weight','both arms','prone'],'muscles':['triceps']},
  {'name':'Tricep Pulldown, Bar','measurement':'reps','mods':['machine','each arm'],'muscles':['triceps']},
  {'name':'Tricep Pulldown, Bar','measurement':'reps','mods':['machine','both arms'],'muscles':['triceps']},
  {'name':'Tricep Pulldown, Rope','measurement':'reps','mods':['machine','both arms'],'muscles':['triceps']},
  {'name':'Tricep Pulldown, Rope','measurement':'reps','mods':['machine','each arm'],'muscles':['triceps']},
  {'name':'V Up','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'V Up, Medicine Ball','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'V Up, Oblique','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'V Up, Physioball','measurement':'reps','mods':['body weight'],'muscles':['abs']},
  {'name':'Wipers, Bent Knee','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Wipers, Straight Leg','measurement':'reps','mods':['body weight'],'muscles':['abs','obliques']},
  {'name':'Wrist Curl','measurement':'reps','mods':['free weight','each arm'],'muscles':['forearms']},
  {'name':'Wrist Curl','measurement':'reps','mods':['free weight','both arms'],'muscles':['forearms']},
  {'name':'Wrist Curl, Reverse','measurement':'reps','mods':['free weight','each arm'],'muscles':['forearms']},
  {'name':'Wrist Curl, Reverse','measurement':'reps','mods':['free weight','both arms'],'muscles':['forearms']},
  {'name':'X Raise','measurement':'reps','mods':['free weight','each arm'],'muscles':['center delts','front delts','rear delts','traps']},
  {'name':'X Raise','measurement':'reps','mods':['free weight','both arms'],'muscles':['center delts','front delts','rear delts','traps']},
  {'name':'X Raise','measurement':'reps','mods':['machine','each arm'],'muscles':['center delts','front delts','rear delts','traps']},
  {'name':'X Raise','measurement':'reps','mods':['machine','both arms'],'muscles':['center delts','front delts','rear delts','traps']},
]

export default EXERCISES;
