const EXERCISES = [
  {'_id':1000000001,'name':'Ab Coaster','measurement':'reps plus','mods':['machine'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000002,'name':'Ab Wheel Rollout','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000003,'name':'Archer Row','measurement':'reps basic','mods':['free weight'],'muscles':['biceps','abs','traps','lats','lower back'],'primaryMuscleGroup':'Full Body'},
  {'_id':1000000004,'name':'Back Extension','measurement':'reps plus','mods':['body weight'],'muscles':['lower back'],'primaryMuscleGroup':'Back'},
  {'_id':1000000005,'name':'Back Extension','measurement':'reps basic','mods':['machine'],'muscles':['lower back'],'primaryMuscleGroup':'Back'},
  {'_id':1000000006,'name':'Backward Leg Extension','measurement':'reps basic','mods':['machine','each leg','prone'],'muscles':['hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000007,'name':'Backward Leg Extension','measurement':'reps basic','mods':['machine','each leg','standing'],'muscles':['hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000008,'name':'Bicep Curl','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000009,'name':'Bicep Curl','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000010,'name':'Bicep Curl','measurement':'reps basic','mods':['machine','iso','each arm'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000011,'name':'Bicep Curl','measurement':'reps basic','mods':['machine','iso','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000012,'name':'Bicep Curl','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000013,'name':'Bicep Curl','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000014,'name':'Bicep Curl','measurement':'reps basic','mods':['machine','each arm','standing'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000015,'name':'Bicep Curl','measurement':'reps basic','mods':['machine','both arms','standing'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000016,'name':'Bicep Curl, Closed Grip','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000017,'name':'Bicep Curl, Closed Grip','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000018,'name':'Bicep Curl, Closed Grip','measurement':'reps basic','mods':['machine','iso','each arm'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000019,'name':'Bicep Curl, Closed Grip','measurement':'reps basic','mods':['machine','iso','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000020,'name':'Bicep Curl, Drag','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['biceps','forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000021,'name':'Bicep Curl, Drag','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['biceps','forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000022,'name':'Bicep Curl, Hammer','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000023,'name':'Bicep Curl, Hammer','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000024,'name':'Bicep Curl, Preacher','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000025,'name':'Bicep Curl, Preacher','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000026,'name':'Bicep Curl, Side','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000027,'name':'Bicep Curl, Side','measurement':'reps basic','mods':['machine','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000028,'name':'Bicep Curl, Wide Grip','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['biceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000029,'name':'Bicep Curl, Zottman','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['biceps','forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000030,'name':'Bicep Curl, Zottman','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['biceps','forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000031,'name':'Bicycles','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000032,'name':'Boat Pose','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000033,'name':'Calf Raise','measurement':'reps plus','mods':['body weight','each leg'],'muscles':['calves'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000034,'name':'Calf Raise','measurement':'reps plus','mods':['body weight','both legs'],'muscles':['calves'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000035,'name':'Calf Raise','measurement':'reps basic','mods':['machine','each leg','sitting'],'muscles':['calves'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000036,'name':'Calf Raise','measurement':'reps basic','mods':['machine','both legs','sitting'],'muscles':['calves'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000037,'name':'Calf Raise','measurement':'reps basic','mods':['machine','each leg','standing'],'muscles':['calves'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000038,'name':'Calf Raise','measurement':'reps basic','mods':['machine','both legs','standing'],'muscles':['calves'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000039,'name':'Chest Press','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000040,'name':'Chest Press','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000041,'name':'Chest Press','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000042,'name':'Chest Press','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000043,'name':'Chest Press','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000044,'name':'Chest Press','measurement':'reps basic','mods':['machine','both arms','standing'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000045,'name':'Chest Press','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000046,'name':'Chest Press, Converging','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000047,'name':'Chest Press, Converging','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000048,'name':'Chest Press, Converging','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000049,'name':'Chest Press, Converging','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000050,'name':'Chest Press, Converging','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000051,'name':'Chest Press, Converging','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000052,'name':'Chest Press, Low Converging','measurement':'reps basic','mods':['machine','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000053,'name':'Chest Press, Low Converging','measurement':'reps basic','mods':['machine','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000054,'name':'Chest Press, Wide','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000055,'name':'Chest Press, Wide','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000056,'name':'Chest Press, Wide','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000057,'name':'Chest Press, Wide','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000058,'name':'Chest Press, Wide','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000059,'name':'Chest Press, Wide','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000060,'name':'Chin Up','measurement':'reps plus','mods':['body weight','both arms'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000061,'name':'Chin Up','measurement':'reps minus','mods':['machine','both arms','assisted'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000062,'name':'Chin Up','measurement':'reps plus','mods':['body weight','each arm'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000063,'name':'Climber Taps','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000064,'name':'Crunch','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000065,'name':'Crunch, Arms High','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000066,'name':'Crunch, Bear','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000067,'name':'Crunch, Cable Pull Down','measurement':'reps basic','mods':['free weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000068,'name':'Crunch, Knee to Elbow','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000069,'name':'Crunch, Physioball','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000070,'name':'Crunch, Raised Knees','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000071,'name':'Crunch, Side','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000072,'name':'Crunchy Frog','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000073,'name':'Dead Bug','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000074,'name':'Dead Lift','measurement':'reps basic','mods':['free weight'],'muscles':['quads','hamstrings','traps','lower back','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000075,'name':'Dead Lift','measurement':'reps basic','mods':['machine'],'muscles':['quads','hamstrings','traps','lower back','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000076,'name':'Dead Lift, Romanian','measurement':'reps basic','mods':['free weight'],'muscles':['quads','hamstrings','traps','lower back','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000077,'name':'Dead Lift, Romanian','measurement':'reps basic','mods':['machine'],'muscles':['quads','hamstrings','traps','lower back','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000078,'name':'Decline Press','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000079,'name':'Decline Press','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000080,'name':'Decline Press','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000081,'name':'Decline Press','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000082,'name':'Decline Press','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000083,'name':'Decline Press','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000084,'name':'Decline Press, Converging','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000085,'name':'Decline Press, Converging','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000086,'name':'Decline Press, Converging','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000087,'name':'Decline Press, Converging','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000088,'name':'Decline Press, Converging','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000089,'name':'Decline Press, Converging','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000090,'name':'Decline Press, Wide','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000091,'name':'Decline Press, Wide','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000092,'name':'Decline Press, Wide','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000093,'name':'Decline Press, Wide','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000094,'name':'Decline Press, Wide','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000095,'name':'Decline Press, Wide','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000096,'name':'Dip, Hanging','measurement':'reps plus','mods':['body weight'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000097,'name':'Dip, Ledge','measurement':'reps plus','mods':['body weight'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000098,'name':'Dip, Seated','measurement':'reps basic','mods':['machine','iso','both arms'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000099,'name':'Elevated Bird Dog','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000100,'name':'Fifer Scissor','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000101,'name':'Flutter Kick','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000102,'name':'Flutter Kick, Boat Pose','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000103,'name':'Front Raise','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['front delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000104,'name':'Front Raise','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['front delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000105,'name':'Front Raise','measurement':'reps basic','mods':['machine','each arm'],'muscles':['front delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000106,'name':'Front Raise','measurement':'reps basic','mods':['machine','both arms'],'muscles':['front delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000107,'name':'Front Raise, Hammer Grip','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['front delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000108,'name':'Front Raise, Hammer Grip','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['front delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000109,'name':'Front Raise, Hammer Grip','measurement':'reps basic','mods':['machine','each arm'],'muscles':['front delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000110,'name':'Front Raise, Hammer Grip','measurement':'reps basic','mods':['machine','both arms'],'muscles':['front delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000111,'name':'Grip Crush','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000112,'name':'Grip Crush','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000113,'name':'Grip Crush','measurement':'reps basic','mods':['machine','each arm'],'muscles':['forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000114,'name':'Grip Crush','measurement':'reps basic','mods':['machine','both arms'],'muscles':['forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000115,'name':'Hamstring Curl','measurement':'reps basic','mods':['machine','each leg','sitting'],'muscles':['hamstrings'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000116,'name':'Hamstring Curl','measurement':'reps basic','mods':['machine','both legs','sitting'],'muscles':['hamstrings'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000117,'name':'Hamstring Curl','measurement':'reps basic','mods':['machine','each leg','prone'],'muscles':['hamstrings'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000118,'name':'Hamstring Curl','measurement':'reps basic','mods':['machine','both legs','prone'],'muscles':['hamstrings'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000119,'name':'Hanging Leg Raise, Bent Knee','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000120,'name':'Hanging Leg Raise, Straight','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000121,'name':'High Pull','measurement':'reps basic','mods':['free weight'],'muscles':['front delts','traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000122,'name':'High Pull','measurement':'reps basic','mods':['machine'],'muscles':['front delts','traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000123,'name':'Hip Flexor','measurement':'reps basic','mods':['machine'],'muscles':['hip flexors'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000124,'name':'Hip Rock N Raise','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000125,'name':'Hip Up','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000126,'name':'Hundreds','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000127,'name':'In and Out','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000128,'name':'Inchworm Slide','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000129,'name':'Incline Press','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000130,'name':'Incline Press','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000131,'name':'Incline Press','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000132,'name':'Incline Press','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000133,'name':'Incline Press','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000134,'name':'Incline Press','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000135,'name':'Incline Press, Converging','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000136,'name':'Incline Press, Converging','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000137,'name':'Incline Press, Converging','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000138,'name':'Incline Press, Converging','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000139,'name':'Incline Press, Converging','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000140,'name':'Incline Press, Converging','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000141,'name':'Incline Press, Wide','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000142,'name':'Incline Press, Wide','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000143,'name':'Incline Press, Wide','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000144,'name':'Incline Press, Wide','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000145,'name':'Incline Press, Wide','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000146,'name':'Incline Press, Wide','measurement':'reps basic','mods':['machine','each arm','sitting'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000147,'name':'Kneeling Chop','measurement':'reps basic','mods':['machine'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000148,'name':'L-Sit','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000149,'name':'Lat Pulldown, Normal','measurement':'reps basic','mods':['machine','both arms'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000150,'name':'Lat Pulldown, Normal','measurement':'reps basic','mods':['machine','iso'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000151,'name':'Lat Pulldown, Normal','measurement':'reps basic','mods':['machine','each arm'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000152,'name':'Lat Pulldown, Normal','measurement':'reps basic','mods':['machine','iso','each arm'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000153,'name':'Lat Pulldown, Palms In','measurement':'reps basic','mods':['machine','both arms'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000154,'name':'Lat Pulldown, Palms In','measurement':'reps basic','mods':['machine','iso'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000155,'name':'Lat Pulldown, Palms In','measurement':'reps basic','mods':['machine','each arm'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000156,'name':'Lat Pulldown, Palms In','measurement':'reps basic','mods':['machine','iso','each arm'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000157,'name':'Lat Pulldown, Wide','measurement':'reps basic','mods':['machine','both arms'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000158,'name':'Lat Pulldown, Wide','measurement':'reps basic','mods':['machine','iso'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000159,'name':'Lat Pulldown, Wide','measurement':'reps basic','mods':['machine','each arm'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000160,'name':'Lat Pulldown, Wide','measurement':'reps basic','mods':['machine','iso','each arm'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000161,'name':'Lateral Raise','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000162,'name':'Lateral Raise','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000163,'name':'Lateral Raise','measurement':'reps basic','mods':['machine','each arm'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000164,'name':'Lateral Raise','measurement':'reps basic','mods':['machine','both arms'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000165,'name':'Lateral Raise, Bent Over','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000166,'name':'Lateral Raise, Bent Over','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000167,'name':'Lateral Raise, Bent Over','measurement':'reps basic','mods':['machine','each arm'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000168,'name':'Lateral Raise, Bent Over','measurement':'reps basic','mods':['machine','both arms'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000169,'name':'Lateral Raise, Hammer Grip','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000170,'name':'Lateral Raise, Hammer Grip','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000171,'name':'Lateral Raise, Hammer Grip','measurement':'reps basic','mods':['machine','each arm'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000172,'name':'Lateral Raise, Hammer Grip','measurement':'reps basic','mods':['machine','both arms'],'muscles':['center delts','rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000173,'name':'Laying Leg Raise, Horizontal','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000174,'name':'Laying Leg Raise, Vertical','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000175,'name':'Laying Toe Taps','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000176,'name':'Leg Climber','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000177,'name':'Leg Press','measurement':'reps basic','mods':['machine','each leg'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000178,'name':'Leg Press','measurement':'reps basic','mods':['machine','both legs'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000179,'name':'Low Pull','measurement':'reps basic','mods':['free weight'],'muscles':['front delts','traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000180,'name':'Low Pull','measurement':'reps basic','mods':['machine'],'muscles':['front delts','traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000181,'name':'Lunge','measurement':'reps plus','mods':['body weight'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000182,'name':'Lunge, Overhead Weight','measurement':'reps basic','mods':['free weight'],'muscles':['center delts','front delts','rear delts','quads','hamstrings','glutes'],'primaryMuscleGroup':'Full Body'},
  {'_id':1000000183,'name':'Mogul Jump','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000184,'name':'Mountain Climbers','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000185,'name':'Opposite Arm/Leg Raise','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000186,'name':'Pectoral Fly','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000187,'name':'Pectoral Fly','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000188,'name':'Pectoral Fly','measurement':'reps basic','mods':['machine','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000189,'name':'Pectoral Fly','measurement':'reps basic','mods':['machine','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000190,'name':'Pectoral Fly, Incline','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000191,'name':'Pectoral Fly, Incline','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000192,'name':'Physioball Buzzsaw','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000193,'name':'Physioball Circles','measurement':'time basic','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000194,'name':'Physioball Pike','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000195,'name':'Pike Press','measurement':'reps plus','mods':['body weight'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000196,'name':'Plank','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000197,'name':'Plank to Down Dog','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000198,'name':'Plank, Arm Raises','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000199,'name':'Plank, Crunches','measurement':'time basic','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000200,'name':'Plank, Leg Raises','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000201,'name':'Plank, Moving Shuffle','measurement':'time basic','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000202,'name':'Plank, RKC','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000203,'name':'Plank, Star','measurement':'time basic','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000204,'name':'Plank, Up and downs','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000205,'name':'Plank, Walk Ins','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000206,'name':'Prone Plate Switch','measurement':'time basic','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000207,'name':'Pull Up','measurement':'reps plus','mods':['body weight','both arms'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000208,'name':'Pull Up','measurement':'reps minus','mods':['machine','both arms','assisted'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000209,'name':'Pull Up','measurement':'reps plus','mods':['body weight','each arm'],'muscles':['biceps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000210,'name':'Pulse Up','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000211,'name':'Pushup','measurement':'reps plus','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000212,'name':'Pushup','measurement':'reps plus','mods':['body weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000213,'name':'Pushup, Cobra','measurement':'reps plus','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000214,'name':'Pushup, Decline','measurement':'reps plus','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000215,'name':'Pushup, Decline','measurement':'reps plus','mods':['body weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000216,'name':'Pushup, Diamond','measurement':'reps plus','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000217,'name':'Pushup, Incline','measurement':'reps plus','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000218,'name':'Pushup, Incline','measurement':'reps plus','mods':['body weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000219,'name':'Pushup, Knees','measurement':'reps plus','mods':['body weight','both arms'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000220,'name':'Pushup, Knees','measurement':'reps plus','mods':['body weight','each arm'],'muscles':['triceps','front delts','pectorals'],'primaryMuscleGroup':'Chest'},
  {'_id':1000000221,'name':'Quadricep Extension','measurement':'reps basic','mods':['machine','each leg'],'muscles':['quads'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000222,'name':'Quadricep Extension','measurement':'reps basic','mods':['machine','both legs'],'muscles':['quads'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000223,'name':'Raised Leg Circles','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000224,'name':'Raised Leg Splits','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000225,'name':'Raised Leg Swings','measurement':'time basic','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000226,'name':'Rear Deltoid Fly','measurement':'reps basic','mods':['machine','both arms'],'muscles':['rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000227,'name':'Rear Deltoid Fly','measurement':'reps basic','mods':['machine','each arm'],'muscles':['rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000228,'name':'Rear Deltoid Fly','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000229,'name':'Rear Deltoid Fly','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['rear delts'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000230,'name':'Reverse Superman','measurement':'time basic','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000231,'name':'Rocky Abs','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000232,'name':'Roman Chair','measurement':'reps plus','mods':['body weight'],'muscles':['lower back'],'primaryMuscleGroup':'Back'},
  {'_id':1000000233,'name':'Rotational Cable Pull','measurement':'reps basic','mods':['machine'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000234,'name':'Row, Bent Over','measurement':'reps basic','mods':['machine','both arms'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000235,'name':'Row, Bent Over','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000236,'name':'Row, Bent Over','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000237,'name':'Row, Face Pull','measurement':'reps basic','mods':['machine','both arms'],'muscles':['traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000238,'name':'Row, Low','measurement':'reps basic','mods':['machine','both arms','sitting'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000239,'name':'Row, Low','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000240,'name':'Row, Low','measurement':'reps basic','mods':['machine','both arms','standing'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000241,'name':'Row, Normal','measurement':'reps basic','mods':['machine','sitting'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000242,'name':'Row, Normal','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000243,'name':'Row, Normal','measurement':'reps basic','mods':['machine','both arms','standing'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000244,'name':'Row, T-Bar (45 deg)','measurement':'reps basic','mods':['machine','both arms'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000245,'name':'Row, T-Bar (45 deg)','measurement':'reps basic','mods':['machine','iso','both arms'],'muscles':['rear delts','traps','lats'],'primaryMuscleGroup':'Back'},
  {'_id':1000000246,'name':'Running Man','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000247,'name':'Russian Twist, Barbell','measurement':'reps basic','mods':['free weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000248,'name':'Russian Twist, Decline Medicine Ball','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000249,'name':'Russian Twist, Medicine Ball','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000250,'name':'Scissor Kick','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000251,'name':'Shoulder Press','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000252,'name':'Shoulder Press','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000253,'name':'Shoulder Press','measurement':'reps basic','mods':['machine','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000254,'name':'Shoulder Press','measurement':'reps basic','mods':['machine','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000255,'name':'Shoulder Press','measurement':'reps basic','mods':['machine','iso','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000256,'name':'Shoulder Press','measurement':'reps basic','mods':['machine','iso','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000257,'name':'Shoulder Press, Hammer Grip','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000258,'name':'Shoulder Press, Hammer Grip','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000259,'name':'Shoulder Press, Hammer Grip','measurement':'reps basic','mods':['machine','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000260,'name':'Shoulder Press, Hammer Grip','measurement':'reps basic','mods':['machine','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000261,'name':'Shoulder Press, Hammer Grip','measurement':'reps basic','mods':['machine','iso','each arm'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000262,'name':'Shoulder Press, Hammer Grip','measurement':'reps basic','mods':['machine','iso','both arms'],'muscles':['triceps','center delts','front delts','rear delts','pectorals'],'primaryMuscleGroup':'Shoulders'},
  {'_id':1000000263,'name':'Shrug, Front','measurement':'reps basic','mods':['free weight'],'muscles':['traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000264,'name':'Shrug, Front','measurement':'reps basic','mods':['machine'],'muscles':['traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000265,'name':'Shrug, Side','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000266,'name':'Shrug, Side','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000267,'name':'Shrug, Side','measurement':'reps basic','mods':['machine','each arm'],'muscles':['traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000268,'name':'Shrug, Side','measurement':'reps basic','mods':['machine','both arms'],'muscles':['traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000269,'name':'Side Jack Knives','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000270,'name':'Side Plank','measurement':'time basic','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000271,'name':'Side Plank, Rotational','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000272,'name':'Single Arm Wall Push','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000273,'name':'Sit up, Butterfly','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000274,'name':'Sit up, Straight Leg','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000275,'name':'Sit up, Wide Leg','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000276,'name':'Sitting Punches','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000277,'name':'Squat','measurement':'reps plus','mods':['body weight'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000278,'name':'Squat','measurement':'reps basic','mods':['machine'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000279,'name':'Squat, Bulgarian Split','measurement':'reps plus','mods':['body weight'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000280,'name':'Squat, Front','measurement':'reps basic','mods':['free weight'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000281,'name':'Squat, Front','measurement':'reps basic','mods':['machine'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000282,'name':'Squat, Jump','measurement':'reps plus','mods':['body weight'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000283,'name':'Squat, Skater','measurement':'reps plus','mods':['body weight'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000284,'name':'Squat, Wall','measurement':'reps plus','mods':['body weight'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000285,'name':'Step up','measurement':'reps plus','mods':['body weight'],'muscles':['quads','hamstrings','glutes'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000286,'name':'Superman','measurement':'time basic','mods':['body weight'],'muscles':['lower back'],'primaryMuscleGroup':'Back'},
  {'_id':1000000287,'name':'Swiss Ball Jack Knife','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000288,'name':'Thigh, Inner','measurement':'reps basic','mods':['machine'],'muscles':['inner thigh'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000289,'name':'Thigh, Outer','measurement':'reps basic','mods':['machine'],'muscles':['outer thigh'],'primaryMuscleGroup':'Legs'},
  {'_id':1000000290,'name':'Trap Raise','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['center delts','front delts','rear delts','traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000291,'name':'Trap Raise','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['center delts','front delts','rear delts','traps'],'primaryMuscleGroup':'Back'},
  {'_id':1000000292,'name':'Tricep Extension','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000293,'name':'Tricep Extension','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000294,'name':'Tricep Extension, Bent Over','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000295,'name':'Tricep Extension, Bent Over','measurement':'reps basic','mods':['machine','each arm'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000296,'name':'Tricep Extension, Bent Over','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000297,'name':'Tricep Extension, Bent Over','measurement':'reps basic','mods':['machine','both arms'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000298,'name':'Tricep Extension, Overhead','measurement':'reps basic','mods':['machine','iso','each arm','sitting'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000299,'name':'Tricep Extension, Overhead','measurement':'reps basic','mods':['machine','iso','both arms','sitting'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000300,'name':'Tricep Extension, Overhead','measurement':'reps basic','mods':['free weight','each arm','sitting'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000301,'name':'Tricep Extension, Overhead','measurement':'reps basic','mods':['free weight','both arms','sitting'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000302,'name':'Tricep Extension, Overhead','measurement':'reps basic','mods':['free weight','each arm','prone'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000303,'name':'Tricep Extension, Overhead','measurement':'reps basic','mods':['free weight','both arms','prone'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000304,'name':'Tricep Pulldown, Bar','measurement':'reps basic','mods':['machine','each arm'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000305,'name':'Tricep Pulldown, Bar','measurement':'reps basic','mods':['machine','both arms'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000306,'name':'Tricep Pulldown, Rope','measurement':'reps basic','mods':['machine','both arms'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000307,'name':'Tricep Pulldown, Rope','measurement':'reps basic','mods':['machine','each arm'],'muscles':['triceps'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000308,'name':'V Up','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000309,'name':'V Up, Medicine Ball','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000310,'name':'V Up, Oblique','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000311,'name':'V Up, Physioball','measurement':'reps plus','mods':['body weight'],'muscles':['abs'],'primaryMuscleGroup':'Core'},
  {'_id':1000000312,'name':'Wipers, Bent Knee','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000313,'name':'Wipers, Straight Leg','measurement':'reps plus','mods':['body weight'],'muscles':['abs','obliques'],'primaryMuscleGroup':'Core'},
  {'_id':1000000314,'name':'Wrist Curl','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000315,'name':'Wrist Curl','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000316,'name':'Wrist Curl, Reverse','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000317,'name':'Wrist Curl, Reverse','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['forearms'],'primaryMuscleGroup':'Arms'},
  {'_id':1000000318,'name':'X Raise','measurement':'reps basic','mods':['free weight','each arm'],'muscles':['center delts','front delts','rear delts','traps'],'primaryMuscleGroup':'Full Body'},
  {'_id':1000000319,'name':'X Raise','measurement':'reps basic','mods':['free weight','both arms'],'muscles':['center delts','front delts','rear delts','traps'],'primaryMuscleGroup':'Full Body'},
  {'_id':1000000320,'name':'X Raise','measurement':'reps basic','mods':['machine','each arm'],'muscles':['center delts','front delts','rear delts','traps'],'primaryMuscleGroup':'Full Body'},
  {'_id':1000000321,'name':'X Raise','measurement':'reps basic','mods':['machine','both arms'],'muscles':['center delts','front delts','rear delts','traps'],'primaryMuscleGroup':'Full Body'},
]

export default EXERCISES;
